# Site settings
title: Scott Thompson
email: swesdssdd@gmail.com
url: https://swesdkts.github.io
description: "Game developer and 3D artist with a background in interactive systems, programming, and real-time 3D. Portfolio featuring game development, technical art, and software-related projects."
keywords: "game development, 3D artist, 3D modeling, game programmer, software development, interactive systems, real-time graphics, technical artist, Unity, C#, programming, game design, tools development, visualization"
skills: "Game Developer | 3D Artist | Programmer"
meta_author: Scott Thompson

# Webmaster tools
google_verify:
bing_verify:

# Contact form
contact: static

# Disqus (optional)
disqus_shortname:

# Color settings
color:
  primary: 18bc9c
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Scott Thompson
  location: Location
  social: Around the Web

# Social links
social:
  - title: github
    url: https://github.com/swesdkts

# Address
address:
  - line: Nebraska

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
- scope:
   path: ""
   type:
   values:
   permalink: ""
